# Generated by Django 4.2.3 on 2023-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(default=44444, upload_to=''),
            preserve_default=False,
        ),
    ]
