# Generated by Django 4.2.3 on 2023-12-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.CharField(default=88888, max_length=100),
            preserve_default=False,
        ),
    ]
