# Generated by Django 4.2.3 on 2023-12-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_person_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='username',
        ),
    ]
